#!/bin/bash

cd /home/backend

. venv/bin/activate

echo 'Running isort'
PYTHONPATH=backend isort .

echo 'Running autoflake'
PYTHONPATH=backend autoflake --in-place --remove-all-unused-imports --recursive .

echo 'Running autopep8'

find . -name '*.py' -not -path './venv/*' -not -path './worker/venv/*' -exec autopep8 --in-place --aggressive --aggressive {} \;

echo 'Script completed'
