#!/bin/bash

cd /home/backend

. venv/bin/activate

echo 'Running isort'
PYTHONPATH=backend isort .

echo 'Running autoflake'
PYTHONPATH=backend autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --exclude venv,worker/venv --recursive .

echo 'Running autopep8'
#PYTHONPATH=backend autopep8 --in-place --recursive --global-config=./pyproject.toml --exclude=./venv --exclude=./worker/venv .
find . -name '*.py' -not -path './venv/*' -not -path './worker/venv/*' -exec autopep8 --in-place --aggressive --aggressive --max-line-length 90 {} \;
