### Accept a team invitation
### Execute ExternalApi/specs/requests/000-Authorization.http before using this!
### Execute ExternalApi/TeamFrontend/specs/send-team-invitation.http before using this to recieve the hash!
POST https://{{host}}/api/team-frontend/accept-team-invitation/{{hash}}
Authorization: Bearer {{jwtToken}}

> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
