### Create fake users
POST https://{{host}}/api/customer-frontend/create-fake-users
Content-Type: application/json

{
    "amount": 2
}


### Create fake teams
POST https://{{host}}/api/customer-frontend/create-fake-teams
Content-Type: application/json

{
    "amount": 2
}


### Create fake tournaments
POST https://{{host}}/api/customer-frontend/create-fake-tournaments
Content-Type: application/json

{
    "amount": 2
}


### Create fake is part of
POST https://{{host}}/api/customer-frontend/create-fake-is-part-of
Content-Type: application/json

{
    "amount": 2
}


### Create fake participates in
POST https://{{host}}/api/customer-frontend/create-fake-participates_in
Content-Type: application/json

{
    "amount": 2
}
