### Creates a passwort reset request
POST https://{{host}}/api/user-frontend/create-password-reset
Content-Type: application/json

{
  "email": "maxi@gmail.de"
}


> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
