### Creates a new passwort from a reset request
### Execute ExternalApi/UserFrontend/specs/create-password-request.http before using this to recieve the hash!
PUT https://{{host}}/api/user-frontend/create-new-password
Content-Type: application/json

{
  "hash": "629cafceb2e74d2bb8dac4840afff36e",
  "password": "123456"
}


> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
