### Returns if the user is an admin of the team
GET https://{{host}}/api/user-frontend/is-admin-of-team/{{escapedName}}


> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
