export enum MealAvailabilityEnum {
  FULL_MEAL_PROVIDED = 'FULL_MEAL_PROVIDED',
  SNACKS = 'SNACKS',
  GRILL_STATION = 'GRILL_STATION',
  NOT_PROVIDED = 'NOT_PROVIDED',
}

export enum GastronomyAvailabilityEnum {
  NEAR_FIELD = 'NEAR_FIELD',
  REACHABLE_IN_5_MINUTES = 'REACHABLE_IN_5_MINUTES',
  REACHABLE_IN_10_MINUTES = 'REACHABLE_IN_10_MINUTES',
  REACHABLE_IN_15_MINUTES = 'REACHABLE_IN_15_MINUTES',
  REACHABLE_IN_20_MINUTES = 'REACHABLE_IN_20_MINUTES',
  MORE_THAN_20_MINUTES = 'MORE_THAN_20_MINUTES',
}
