### Log user in and save JWT token
POST https://{{host}}/api/customer-frontend/login
Content-Type: application/json

{
    "username": "Maxi",
    "password": "123456"
}

> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("jwtToken", response.body.token);
%}
