### Bekomme alle Daten
GET https://{{host}}/api/data-text


### Füge Item hinzu
POST https://{{host}}/api/items
Content-Type: application/json

{
    "name": "Item 1"
}


### Bekomme alle Items
GET https://{{host}}/api/items


### Generate fake users
POST https://{{host}}/api/generate-fake-users
Content-Type: application/json

{
    "count": 2
}


### Generate fake teams
POST https://{{host}}/api/generate-fake-teams
Content-Type: application/json

{
    "count": 2
}


### Generate fake tournaments
POST https://{{host}}/api/generate-fake-tournaments
Content-Type: application/json

{
    "count": 2
}


### Generate fake is part of
POST https://{{host}}/api/generate-fake-is-part-of
Content-Type: application/json

{
    "count": 2
}


### Generate fake is part of
POST https://{{host}}/api/generate-fake-participates_in
Content-Type: application/json

{
    "count": 2
}
