### Bekomme alle Daten
GET https://{{host}}/api/data-text


### Füge Item hinzu
POST https://{{host}}/api/items
Content-Type: application/json

{
    "name": "Item 1"
}


### Bekomme alle Items
GET https://{{host}}/api/items

